[2024-08-18T08:23:07.259+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-18T08:23:07.271+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid2hive.process2hive manual__2024-08-18T08:23:06.536498+00:00 [queued]>
[2024-08-18T08:23:07.276+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid2hive.process2hive manual__2024-08-18T08:23:06.536498+00:00 [queued]>
[2024-08-18T08:23:07.277+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-18T08:23:07.284+0000] {taskinstance.py:2879} INFO - Executing <Task(SSHOperator): process2hive> on 2024-08-18 08:23:06.536498+00:00
[2024-08-18T08:23:07.287+0000] {standard_task_runner.py:72} INFO - Started process 348 to run task
[2024-08-18T08:23:07.290+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'covid2hive', 'process2hive', 'manual__2024-08-18T08:23:06.536498+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/covid2hive.py', '--cfg-path', '/tmp/tmpbx_xyc_7']
[2024-08-18T08:23:07.291+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask process2hive
[2024-08-18T08:23:07.319+0000] {task_command.py:467} INFO - Running <TaskInstance: covid2hive.process2hive manual__2024-08-18T08:23:06.536498+00:00 [running]> on host 76ff1c69b8e4
[2024-08-18T08:23:07.373+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ren294' AIRFLOW_CTX_DAG_ID='covid2hive' AIRFLOW_CTX_TASK_ID='process2hive' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T08:23:06.536498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-18T08:23:06.536498+00:00'
[2024-08-18T08:23:07.374+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-18T08:23:07.382+0000] {ssh.py:151} INFO - Creating ssh_client
[2024-08-18T08:23:07.382+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2024-08-18T08:23:07.393+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in get_ssh_client
    return self.hook.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 143, in hook
    return self.ssh_hook
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 125, in ssh_hook
    hook = SSHHook(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/hooks/ssh.py", line 154, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `ssh_spark_master` isn't defined
[2024-08-18T08:23:07.397+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=covid2hive, task_id=process2hive, run_id=manual__2024-08-18T08:23:06.536498+00:00, execution_date=20240818T082306, start_date=20240818T082307, end_date=20240818T082307
[2024-08-18T08:23:07.407+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-18T08:23:07.408+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task process2hive (The conn_id `ssh_spark_master` isn't defined; 348)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in get_ssh_client
    return self.hook.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 143, in hook
    return self.ssh_hook
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 125, in ssh_hook
    hook = SSHHook(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/hooks/ssh.py", line 154, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `ssh_spark_master` isn't defined
[2024-08-18T08:23:07.429+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-18T08:23:07.441+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-18T08:23:07.442+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
